prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  sidecar:
    datasources:
      uid: Prometheus
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      uid: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
      jsonData:
        manageAlerts: false
        derivedFields:
          - name: transfer_id
            matcherRegex: '"transfer_id":"([^"]+)"'
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
          spanStartTimeShift: "-5m"
          spanEndTimeShift: "5m"
          filterByTraceID: true
        serviceMap:
          datasourceUid: Prometheus
