prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      uid: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc.cluster.local
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
