tempo:
  reportingEnabled: false
  retention: 24h
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://monitoring-kube-prometheus-prometheus.monitoring:9090/api/v1/write

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 5Gi
