apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bank-flow-http-routes
  namespace: default
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: bank-flow-rate-limiting
spec:
  parentRefs:
    - name: kong
      namespace: kong
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /transfer
      backendRefs:
        - name: bank-flow-transfer
          kind: Service
          port: 8083