apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: bank-flow-transfer-rate-limiting
  namespace: bank-flow
plugin: rate-limiting
config:
  minute: 1200
  hour: 30000
  limit_by: ip
  policy: local
  fault_tolerant: true
  hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: bank-flow-accounts-rate-limiting
  namespace: bank-flow
plugin: rate-limiting
config:
  minute: 600
  hour: 12000
  limit_by: ip
  policy: local
  fault_tolerant: true
  hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: bank-flow-balance-rate-limiting
  namespace: bank-flow
plugin: rate-limiting
config:
  minute: 1200
  hour: 30000
  limit_by: ip
  policy: local
  fault_tolerant: true
  hide_client_headers: false
