nameOverride: bank-flow-outboxer

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

pdb:
  enabled: true
  minAvailable: 1

image:
  repository: gbcamargo/bank-flow-outboxer
  tag: 1.1.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8088

metrics:
  job: bank-flow-services

serviceMonitor:
  enabled: true
  namespace: "bank-flow"
  interval: 15s
  scrapeTimeout: 10s
  path: /actuator/prometheus
  labels:
    release: monitoring

probe:
  enabled: true
  namespace: "bank-flow"
  jobName: bank-flow-health
  module: http_2xx
  proberUrl: prometheus-blackbox-exporter.monitoring.svc:9115
  targetPath: /actuator/health
  interval: 15s
  scrapeTimeout: 10s
  labels:
    release: monitoring

env:
  SERVER_PORT: "8088"
  POSTGRES_URL: "jdbc:postgresql://host.docker.internal:5432/bank_flow?currentSchema=outboxer,public"
  KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9094"
  OUTBOX_PUBLISHER_FIXED_DELAY_MS: "500"
  OUTBOX_PUBLISHER_BATCH_SIZE: "200"
  OUTBOX_PUBLISHER_LOCK_LEASE_MS: "60000"
  OUTBOX_PUBLISHER_SEND_TIMEOUT_MS: "30000"
  OUTBOX_PUBLISHER_MAX_ATTEMPTS: "10"
  KAFKA_PRODUCER_MAX_BLOCK_MS: "30000"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
  MANAGEMENT_HEALTH_SHOW_DETAILS: "never"
  BPL_JVM_THREAD_COUNT: "50"
  HIKARI_MAXIMUM_POOL_SIZE: "4"
  HIKARI_MINIMUM_IDLE: "1"
  HIKARI_CONNECTION_TIMEOUT_MS: "2000"
  HIKARI_IDLE_TIMEOUT_MS: "600000"
  HIKARI_MAX_LIFETIME_MS: "1500000"
  LOG_FILE: ""

secretEnv:
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mysecretpassword"

readinessProbe:
  path: /actuator/health/readiness
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6

livenessProbe:
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

resources:
  requests:
    cpu: 150m
    memory: 384Mi
  limits:
    cpu: 750m
    memory: 768Mi
