{{- range $componentKey, $component := .Values.components }}
{{- if $component.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $component.name }}
  labels:
    app.kubernetes.io/name: {{ $component.name }}
    app.kubernetes.io/component: {{ $componentKey }}
    app.kubernetes.io/part-of: bank-flow
spec:
  {{- if not (or $component.autoscaling.enabled $component.keda.enabled) }}
  replicas: {{ $component.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $component.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $component.name }}
        app.kubernetes.io/component: {{ $componentKey }}
        app.kubernetes.io/part-of: bank-flow
    spec:
      containers:
        - name: {{ $component.name }}
          image: "{{ $component.image.repository }}:{{ $component.image.tag }}"
          imagePullPolicy: {{ $component.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $component.service.port }}
          envFrom:
            - configMapRef:
                name: {{ $component.name }}-config
            - secretRef:
                name: {{ $.Values.nameOverride }}-secret
          readinessProbe:
            httpGet:
              path: {{ $component.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ $component.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $component.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $component.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $component.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ $component.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ $component.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $component.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $component.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $component.livenessProbe.failureThreshold }}
          resources:
{{ toYaml $component.resources | indent 12 }}
---
{{- end }}
{{- end }}
