{{- range $componentKey, $component := .Values.components }}
{{- if $component.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $component.name }}
  labels:
    app.kubernetes.io/name: {{ $component.name }}
    app.kubernetes.io/component: {{ $componentKey }}
    app.kubernetes.io/part-of: bank-flow
    prometheus-job: {{ $.Values.metrics.job | quote }}
    service: {{ $component.name }}
    stack: bank-flow
spec:
  type: {{ $component.service.type }}
  selector:
    app.kubernetes.io/name: {{ $component.name }}
  ports:
    - name: http
      port: {{ $component.service.port }}
      targetPort: http
---
{{- end }}
{{- end }}
