{{- if .Values.probe.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ .Values.nameOverride }}-health
  {{- if .Values.probe.namespace }}
  namespace: {{ .Values.probe.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: bank-flow
{{- range $key, $value := .Values.probe.labels }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  jobName: {{ .Values.probe.jobName }}
  module: {{ .Values.probe.module }}
  prober:
    url: {{ .Values.probe.proberUrl }}
  targets:
    staticConfig:
      static:
        - http://{{ .Values.nameOverride }}.{{ .Release.Namespace }}.svc:{{ .Values.service.port }}{{ .Values.probe.targetPath }}
      labels:
        service: {{ .Values.nameOverride }}
        stack: bank-flow
{{- end }}
