{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.nameOverride }}-scaledobject
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: bank-flow
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: {{ .Values.nameOverride }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
{{ toYaml .Values.keda.triggers | indent 4 }}
{{- end }}
