{{- $worker := .Values.components.worker }}
{{- if and $worker.enabled $worker.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $worker.name }}-scaledobject
  labels:
    app.kubernetes.io/name: {{ $worker.name }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: bank-flow
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ $worker.name }}
  minReplicaCount: {{ $worker.keda.minReplicaCount }}
  maxReplicaCount: {{ $worker.keda.maxReplicaCount }}
  pollingInterval: {{ $worker.keda.pollingInterval }}
  cooldownPeriod: {{ $worker.keda.cooldownPeriod }}
  triggers:
{{ toYaml $worker.keda.triggers | indent 4 }}
{{- end }}
