spring.application.name=bank-flow-auth
server.port=${SERVER_PORT:8090}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_flow_auth?currentSchema=auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:backend}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:backend}

spring.flyway.enabled=true
spring.flyway.schemas=auth
spring.flyway.default-schema=auth
spring.flyway.create-schemas=true

app.auth.issuer-key=${AUTH_ISSUER_KEY:local-dev-issuer-key}
app.auth.jwt.issuer=${AUTH_JWT_ISSUER:http://localhost:8090}
app.auth.jwt.key-id=${AUTH_JWT_KEY_ID:bank-flow-auth-dev}
app.auth.jwt.private-key=${AUTH_JWT_PRIVATE_KEY:}
app.auth.jwt.ttl=${AUTH_JWT_TTL:15m}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.otlp.metrics.export.enabled=false
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=${MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT:http://localhost:14318/v1/traces}
management.observations.key-values.application=${spring.application.name}
