spring.application.name=bank-flow-transfer

server.port=${SERVER_PORT:8083}

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/bank_flow?currentSchema=transfer,public}
spring.datasource.username=${POSTGRES_USER:myuser}
spring.datasource.password=${POSTGRES_PASSWORD:mysecretpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=transfer
spring.flyway.default-schema=transfer
spring.flyway.create-schemas=true
spring.flyway.baseline-on-migrate=false

bank-flow.balance.base-url=${BALANCE_BASE_URL:http://localhost:8082}
bank-flow.psp.mode=${PSP_MODE:mock}
bank-flow.psp.base-url=${PSP_BASE_URL:http://localhost:9099}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
