apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.nameOverride }}
    app.kubernetes.io/part-of: bank-flow
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
