name: Balance Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/balance-api-pipeline.yaml

  worker:
    uses: ./.github/workflows/balance-worker-pipeline.yaml
