name: Deploy ledger

on:
  workflow_call:
    inputs:
      ambiente:
        required: true
        type: string
        default: 'staging'
    secrets:
      TOKEN_SECRET:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executando Deploy
        run: echo "Deploying to ${{ inputs.ambiente }}"