name: Outboxer Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: bank-flow-outboxer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bank-flow-outboxer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Run tests
        run: ./gradlew test
