name: Bank Flow Services

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Servico para testar"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - accounts
          - balance
          - transfer
          - ledger

jobs:
  accounts:
    if: ${{ inputs.service == 'all' || inputs.service == 'accounts' }}
    uses: ./.github/workflows/accounts-pipeline.yaml

  balance:
    if: ${{ inputs.service == 'all' || inputs.service == 'balance' }}
    uses: ./.github/workflows/balance-pipeline.yaml

  transfer:
    if: ${{ inputs.service == 'all' || inputs.service == 'transfer' }}
    uses: ./.github/workflows/transfer-pipeline.yaml

  ledger:
    if: ${{ inputs.service == 'all' || inputs.service == 'ledger' }}
    uses: ./.github/workflows/ledger-pipeline.yaml
