name: Orquestrador Principal

on:
  workflow_dispatch: # Adiciona o botão "Run workflow" na aba Actions
    inputs:
      target_env:
        description: 'Ambiente de Deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  ledger-pipeline:
    uses: ./.github/workflows/ledger-pipeline.yaml
    with:
      ambiente: ${{ github.event.inputs.target_env }}