name: Transfer Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  api:
    uses: ./.github/workflows/transfer-api-pipeline.yaml

  worker:
    uses: ./.github/workflows/transfer-worker-pipeline.yaml
